# Generated by Django 2.2.2 on 2020-01-12 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='文件夹名字', max_length=20, verbose_name='文件夹名字')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('last_time', models.DateTimeField(default=datetime.datetime.now, help_text='最新时间', verbose_name='最新时间')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
            },
        ),
    ]
