# Generated by Django 2.2.2 on 2020-01-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='文件夹名字', max_length=100, verbose_name='文件夹名字'),
        ),
    ]
