# Generated by Django 2.2.2 on 2020-01-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='20200127', help_text='时间', max_length=100, verbose_name='时间')),
                ('login_count', models.IntegerField(default=0)),
                ('upload_count', models.IntegerField(default=0)),
                ('knowpic_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('translate_count', models.IntegerField(default=0)),
                ('entitynaming_count', models.IntegerField(default=0)),
            ],
        ),
    ]
