# Generated by Django 2.2.2 on 2020-01-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20200127_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincountmodel',
            name='download_count',
            field=models.IntegerField(default=0, help_text='下载次数', verbose_name='下载次数'),
        ),
        migrations.AlterField(
            model_name='admincountmodel',
            name='data',
            field=models.CharField(default='2020/01/27', help_text='时间', max_length=100, verbose_name='时间'),
        ),
    ]
