# Generated by Django 2.2.2 on 2020-03-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20200128_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincountmodel',
            options={'verbose_name': '功能调用统计', 'verbose_name_plural': '功能调用统计'},
        ),
    ]
