# Generated by Django 2.2.2 on 2020-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20200311_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincountmodel',
            name='checkdocument_count',
            field=models.IntegerField(default=0, help_text='文章审核', verbose_name='文章审核'),
        ),
        migrations.AddField(
            model_name='admincountmodel',
            name='sentiment_count',
            field=models.IntegerField(default=0, help_text='情感倾向', verbose_name='情感倾向'),
        ),
        migrations.AddField(
            model_name='admincountmodel',
            name='summary_count',
            field=models.IntegerField(default=0, help_text='摘要', verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='admincountmodel',
            name='type_count',
            field=models.IntegerField(default=0, help_text='自动分类', verbose_name='自动分类'),
        ),
    ]
