# Generated by Django 2.2.2 on 2020-04-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20200409_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincountmodel',
            name='read_count',
        ),
    ]
