# Generated by Django 2.2.2 on 2020-01-12 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章标题', max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, help_text='文案内容', null=True, verbose_name='文案内容')),
                ('upload_type', models.IntegerField(choices=[(0, '识别上传'), (1, '非识别上传')], default=1, help_text='上传方式(0,识别上传; 1,非识别上传)', verbose_name='上传方式')),
                ('translate_count', models.IntegerField(default=0, help_text='调用翻译次数', verbose_name='调用翻译次数')),
                ('read_count', models.IntegerField(default=0, help_text='调用语音次数', verbose_name='调用语音次数')),
                ('pickword_count', models.IntegerField(default=0, help_text='调用实体命名次数', verbose_name='调用实体命名次数')),
                ('starlevel', models.IntegerField(choices=[(1, '星级1'), (2, '星级2'), (3, '星级3'), (4, '星级4'), (5, '星级5')], default=1, help_text='星级(1,2,3,4,5)', verbose_name='星级')),
                ('wordcount', models.IntegerField(default=0, help_text='文章字数', verbose_name='文章字数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('last_time', models.DateTimeField(default=datetime.datetime.now, help_text='最新时间', verbose_name='最新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
