# Generated by Django 2.2.2 on 2020-01-27 17:55

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200113_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, help_text='文案内容', null=True, verbose_name='文案内容'),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
    ]
