# Generated by Django 2.2.2 on 2020-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20200316_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='', help_text='文章种类', max_length=50, verbose_name='文章种类'),
        ),
    ]
