# Generated by Django 2.2.2 on 2020-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sentiment',
            field=models.CharField(default='', help_text='文章情感', max_length=50, verbose_name='文章情感'),
        ),
    ]
