# Generated by Django 2.2.2 on 2020-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200113_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pickword_count',
            field=models.IntegerField(default=0, help_text='调用实体命名次数', verbose_name='调用实体命名次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='read_count',
            field=models.IntegerField(default=0, help_text='调用语音次数', verbose_name='调用语音次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='translate_count',
            field=models.IntegerField(default=0, help_text='调用翻译次数', verbose_name='调用翻译次数'),
        ),
    ]
