# Generated by Django 2.2.2 on 2020-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200126_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document_count',
            field=models.IntegerField(default=0, help_text='文章数量', verbose_name='文章数量'),
        ),
    ]
