# Generated by Django 2.2.2 on 2020-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200127_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='read_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='checkdocument_count',
            field=models.IntegerField(default=0, help_text='文章审核', verbose_name='文章审核'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='download_count',
            field=models.IntegerField(default=0, help_text='下载次数', verbose_name='下载次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entitynaming_count',
            field=models.IntegerField(default=0, help_text='实体命名', verbose_name='实体命名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='knowpic_count',
            field=models.IntegerField(default=0, help_text='使用识别次数', verbose_name='使用识别次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sentiment_count',
            field=models.IntegerField(default=0, help_text='情感倾向', verbose_name='情感倾向'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='summary_count',
            field=models.IntegerField(default=0, help_text='摘要', verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_count',
            field=models.IntegerField(default=0, help_text='自动分类', verbose_name='自动分类'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upload_count',
            field=models.IntegerField(default=0, help_text='上传次数', verbose_name='上传次数'),
        ),
    ]
