# Generated by Django 2.2.2 on 2020-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20200419_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='entitynaming_count',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pickword_count',
            field=models.IntegerField(default=0, help_text='关键词提取', verbose_name='关键词提取'),
        ),
    ]
